### ISSUE TITLE
Исправить компонент AGWCatigories

### ISSUE THREAD

**Issue by fiersik** [OlegShchavelev/ALTRegularGnomeWiki#177]
На странице [wiki](https://alt-gnome.wiki/wiki.html) используется Frontmatter переменная `title` для названия раздела:

```yaml
---
aside: false
docs:
    - categories:
        title: Быстрый старт
---
```

Но вместо использования данной переменной, в компоненте AGWCatigories на прямую указано `Быстрый старт`

```vue
<template>
    <div v-if="items" class="AGWCatigories">
        <h2>Быстрый старт</h2>
        <div class="items">
            <div v-for="item in items" :key="item.title" class="item grid-4">
                <AGWCategory :title="item.title" :icon="item.icon" :apps="item.apps" />
            </div>
        </div>
    </div>
</template>
```
